### ISSUE TITLE
[must-have] Customizing Colors in Tailwind

### ISSUE THREAD

**Issue by sergeyzoloto** [organizer-team/organizer#11]
`const colorPalette = {
  primaryColor: '#9747FF',
  lighterShade: '#B580FF',
  darkerShade: '#6E24B1',
  accentLightPurple: '#C996FF',
  accentDarkPurple: '#7A1FC3',
  neutralLightGray: '#F2F2F2',
  neutralDarkGray: '#333333',
};
`

[tailwind docs](https://tailwindcss.com/docs/customizing-colors)

**Comment by Ozgur2096** [comment]
Completed
