### ISSUE TITLE
[must-have] Welcome Page

### ISSUE THREAD

**Issue by Ozgur2096** [organizer-team/organizer#26]
1. It should have a text about the app and the welcome page
2. It should look nice because it will be the first page that the user sees. 
3. There should be two option (button): Guest (demo) and User (for the people who have an account or want to have an account).
4. "Continue as a guest" button should redirects to Home Page with a temporary token (email and password should create in the database for a short time and later it should be deleted automatilcally). The user has no idea about email and password but it will work in the background.
5. "Continue as an user" button should redirects to Email Validation page.

**Comment by sergeyzoloto** [comment]
done
