### ISSUE TITLE
[must-have] Create User Page

### ISSUE THREAD

**Issue by sergeyzoloto** [organizer-team/organizer#4]
1. Create the user interface for account creation. This should include fields for the user to enter their

- name
- email
- password
- confirm password

2. The page should be accessible at /user/signup
3. There should be a form confirmation button on the page.
~~4. The page should have a link to the login page.~~
5. Items need to be arranged vertically for the mobile version.
6. Write unit tests.

**Comment by Ozgur2096** [comment]
Completed except testing

**Comment by sergeyzoloto** [comment]
done
